### ISSUE TITLE
Comments on the EM semantic model

### ISSUE THREAD

**Issue by oolonek** [digital-botanical-gardens-initiative/earth_metabolome_ontology#1]
@tarcisiotmf it looks interesting !

Some thoughts looking at the [SOSA](https://www.w3.org/TR/vocab-ssn/#SOSASampler)

I am not sure where to put an LCMS platform because it is actually :
- definitively a `Sensor` https://www.w3.org/TR/vocab-ssn/#SOSASensor
but also : 
- a `Sampler` https://www.w3.org/TR/vocab-ssn/#SOSASampler (e.g. you aliquot 2microL of the whole sample before injecting)
- an `Actuator` https://www.w3.org/TR/vocab-ssn/#SOSAActuator (e.g. in the sense, how they phrase it, that it "changes the state of the world". The sample will be physically separated during the Liquid Chromatography (LC) run, the analytes will be ionized (in the source), the pool of ion will be further physically separated in the MS analyzer, or even broken down in smaller sub-molecular pieces when using fragmentation mode). 

Not sure if we need to be that precise at the moment but it is worth keeping in mind for sure (would ease the collection of experimental parameters such as LC part, ionization part, acquisition modes etc.)

Considering that humans can be considered as Sensors also (https://www.w3.org/TR/vocab-ssn/#SOSASensor) and a Sampler ? (https://www.w3.org/TR/vocab-ssn/#SOSASampler) maybe we could extend this model to also integrate researchers observing and sampling the biodiversity ?

**Comment by tarcisiotmf** [comment]
comments added and version 0.2 including pairwise interactions modelling released today
