### ISSUE TITLE
Document the Ontop process

### ISSUE THREAD

**Issue by oolonek** [digital-botanical-gardens-initiative/earth_metabolome_ontology#5]
- what are the principles of Ontop
- wht are the advantages on Ontop
- what are the limitations of Ontop
- how to edit a ontop binding (SQL-SPARQL) in Protegé or elsewere
- how to contribute

**Comment by tarcisiotmf** [comment]
It is now available at https://github.com/digital-botanical-gardens-initiative/earth_metabolome_ontology/blob/main/README.md
